apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  namespace: default
  annotations:
    backstage.io/managed-by-location: url:https://github.com/oliverdirks/mkdocs-example/tree/master/catalog-info.yaml
    backstage.io/managed-by-origin-location: url:https://github.com/oliverdirks/mkdocs-example/blob/master/catalog-info.yaml
    backstage.io/view-url: https://github.com/oliverdirks/mkdocs-example/tree/master/catalog-info.yaml
    backstage.io/edit-url: https://github.com/oliverdirks/mkdocs-example/edit/master/catalog-info.yaml
    backstage.io/source-location: url:https://github.com/oliverdirks/mkdocs-example/tree/master/
    backstage.io/techdocs-ref: dir:.
  name: mkdocs-example
  description: example mkdocs repository
spec:
  type: library
  owner: CNCF
  lifecycle: experimental
